#pragma once

#include <string>
#include <cstdlib>
#include <format>
#include "root_directory.h" // This is a configuration file generated by CMake.

#ifdef _WIN32
    const char PATH_SEP = '\\';
#else
    const char PATH_SEP = '/';
#endif

void replaceAll(std::string& str, const std::string& from, const std::string& to) {
    size_t start_pos = 0;
    while((start_pos = str.find(from, start_pos)) != std::string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length(); // Move past the new replacement
    }
}

class FileSystem
{
private:
    typedef std::string (*Builder) (const std::string& path);

public:
    static std::string getPath(const std::string& path)
    {
        static std::string(*pathBuilder)(std::string const &) = getPathBuilder();
        return (*pathBuilder)(path);
    }

private:
    static std::string const & getRoot()
    {
        static char const * envRoot = getenv("LOGL_ROOT_PATH");
        static char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
        static std::string root = (givenRoot != nullptr ? givenRoot : "");
        return root;
    }

    //static std::string(*foo (std::string const &)) getPathBuilder()
    static Builder getPathBuilder()
    {
        if (getRoot() != "")
            return &FileSystem::getPathRelativeRoot;
        else
            return &FileSystem::getPathRelativeBinary;
    }

    static std::string getPathRelativeRoot(const std::string& path)
    {
        std::string universalPath = path;
        replaceAll(universalPath, "/", std::string(1, PATH_SEP));
        return getRoot() + std::string(1, PATH_SEP) + universalPath;
    }

    static std::string getPathRelativeBinary(const std::string& path)
    {
        std::string universalPath = path;
        replaceAll(universalPath, "/", std::string(1, PATH_SEP));
        return ".." + std::string(1, PATH_SEP) + ".." + std::string(1, PATH_SEP) + ".." + std::string(1, PATH_SEP) + universalPath;
    }
};
